### ISSUE TITLE
Error: Member not found: 'Hooks.create'

### ISSUE THREAD

**Issue by houxinli** [Skycoder42/dart_pre_commit#15]
New to this libarary. The method in README mostly does not work...
Windows 10. dart_pre_commit 3.0.0

**Comment by houxinli** [comment]
git_hooks_0.1.3-nullsafety.0

**Comment by Skycoder42** [comment]
Oh, my bad. I guess I forgot to update that part of the readme when changing the APIs. Have a look at the [Example](https://github.com/Skycoder42/dart_pre_commit/blob/master/example/main.dart), there you can find how to use the library. You will have to install [riverpod](https://pub.dev/packages/riverpod) as well.

**Comment by Skycoder42** [comment]
With the 4.0.0 release, the public API has changed. It is now correctly referenced in the README and the example
