### ISSUE TITLE
dart format line length option

### ISSUE THREAD

**Issue by nzoschke** [Skycoder42/dart_pre_commit#16]
I prefer my project to have > 80 char line length. 

`dart format --line-length 150` in combination with [VS Code settings outlined here](https://stackoverflow.com/questions/59456452/how-to-change-dart-line-length-in-vscode-when-formatting-dart-files) works, but I don't see how to pass the `--line-length` option down to the pre-commit hook.

**Comment by nzoschke** [comment]
As a workaround I am doing this in my `commit` script

```bash
#!/bin/bash
set -ex

dart format --fix -l 150
dart pub run dart_pre_commit --no-format
```

**Comment by Skycoder42** [comment]
I am currently working on version 4.0. In that version, the whole configuration system will be overhauled. As part of this, I will add support for configuring the format task.

**Comment by nzoschke** [comment]
This is working as expected and documented in 4.0 with this in my pubspec.yml

```yaml
dart_pre_commit:
  format:
    line-length: 150
```

And back to `dart run dart_pre_commit` in `pre-commit`.

Thank you for this excellent tool.
