### ISSUE TITLE
lib-exports on flutter skeleton app

### ISSUE THREAD

**Issue by nzoschke** [Skycoder42/dart_pre_commit#17]
A flutter skeleton creates public `MyApp` class that consumes a public `SampleItemListView` class. These aren't exported and I'm not sure it makes sense to do so for a flutter app. 

Should the lib-exports script handle this different? Should I start exporting my Flutter app components? Should I just not use the lib-exports script for flutter? Perhaps documenting this is the solution.

```
dart run dart_pre_commit -l debug
...
🔎 Running lib-exports...
    lib/src/app.dart:10:1 - File has package-public declaration
    lib/src/sample_feature/sample_item_list_view.dart:7:1 - File has package-public declaration
    lib/src/app.dart - Source file is not exported anywhere
    lib/src/sample_feature/sample_item_list_view.dart - Source file is not exported anywhere
❌ Completed lib-exports, found problems
```

**Comment by Skycoder42** [comment]
Yes, this indeed only makes sense for packages that get published to pub.dev. I will implement a check in the tool that only loads the task if the `publish_to` is not set to `none` (as recommended for standard flutter apps). For your case, you can simply disable it.

**Comment by Skycoder42** [comment]
@nzoschke With 4.0.0, the job should not run anymore, as long as `publish_to: none` is set in the pubspec

**Comment by nzoschke** [comment]
Confirmed in 4.0 the simple `dart run dart_pre_commit` command is working on an app with `publish_to` `none`.

Thanks!
